title: Hannah Weitz
author: Hannah Weitz
description: Art
aboutme: >-
  Hannah Weitz chases impressions, feelings and thoughts in a person's eye. Her incisive watercolor-portraits aim to provoke a deep sense of fascination and reflection in the viewer. The colourful display contrasts the quiet presentation of feelings and thoughts. Different expressions and cultural backgrounds featured in her work highlight the beauty of variety and peaceful coexistence as well as the unique nature of growing old. Regardless of origin, age or gender, there is and always will be a fascinating beauty in every person. Hannah Weitz hunts this down, capturing small but beautiful details in the translucent mode of watercolor.
  <br> <br> Self-taught, she is proud to base her whole artistic progress on her talent and discipline as well as the willingness to accept errors in her learning process. She started with pencil drawings in her childhood, later worked with carcoal and focussed on watercolors for several years. As she is open to new, sophisticated drawing and painting styles, she recently started working on a series of oil paintings focussing on the naked female body, movements and self-conscience.
  <br> Still highlighting the beauty of women in her most recent oil paintings, the artist invites to rethink the image of women in the society, which she perceives in seeing solely the female body as a subject of importance. Incentivising the viewer to reflect on this apparent perspective is the main goal of her upcoming work, which will be released in the upcoming month.

social:
  email: hannah.y.weitz@gmail.com
  twitter:
  facebook:
  instagram: hannahwtz
  github:
  linkedin:
  pinterest:

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  images:
    output: true

include: ['.htaccess']
